# Generated by Django 5.1.5 on 2025-01-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_caja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
