# Generated by Django 5.1.5 on 2025-01-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_cliente_venta_productoventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='ProductoVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
